# SwiftLint configuration
# For all rules, see https://realm.github.io/SwiftLint/rule-directory.html

# We adopt the default rules and then customize them below.
# To see the current list, run `swiftlint rules`

disabled_rules:
  - trailing_whitespace # Handled by SwiftFormat

opt_in_rules:
  - closure_end_indentation
  - closure_spacing
  - empty_count
  - explicit_init
  - fatal_error_message
  - file_header
  - first_where
  - force_unwrapping
  - implicitly_unwrapped_optional
  - nimble_operator
  - operator_usage_whitespace
  - overridden_super_call
  - private_outlet
  - prohibited_super_call
  - quick_discouraged_call
  - redundant_nil_coalescing
  - sorted_imports
  - switch_case_on_newline
  - unneeded_parentheses_in_closure_argument
  - vertical_whitespace_closing_braces
  - yoda_condition

# Paths to ignore when linting. Takes precedence over `included`.
excluded:
  - Carthage/
  - Pods/
  - .build/
  - derived_data/

# Rule-specific configurations
line_length: 120
file_length:
  warning: 500
  error: 800
type_body_length:
  warning: 400
  error: 600
function_body_length:
  warning: 50
  error: 100
type_name:
  min_length: 3
  max_length:
    warning: 40
    error: 50
identifier_name:
  min_length:
    warning: 2
  excluded:
    - id
    - to
    - db
reporter: "xcode" # reporter type (xcode, json, csv, checkstyle, junit, html, emoji)
